### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by lwj7790** [lwj7790/Smart-home-using-deep-learning#2]
python lsp_dataset.py

Traceback (most recent call last):
  File "lsp_dataset.py", line 13, in <module>
    from scripts.config import *
ImportError: No module named 'scripts'

      python3 lsp_dataset.py 

Traceback (most recent call last):
  File "lsp_dataset.py", line 13, in <module>
    from scripts.config import *
ImportError: No module named 'scripts'

**Comment by lwj7790** [comment]
'pwd', use output of 

      $ pwd
